[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.31.0"

# CI backends to support
ci = "github"

# The installers to generate for each app
installers = ["shell", "powershell", "homebrew"]

# Homebrew tap to publish the generated formula to
tap = "NetsoftHoldings/homebrew-tap"

# Publish jobs to enable
publish-jobs = ["homebrew"]

# Target platforms to build apps for (Rust target-triple syntax)
targets = [
  "aarch64-apple-darwin",
  "aarch64-unknown-linux-gnu",
  "x86_64-apple-darwin",
  "x86_64-pc-windows-msvc",
  "x86_64-unknown-linux-gnu",
]

# Allow manual edits to the generated release.yml (we add --draft to gh release create)
allow-dirty = ["ci"]

[dist.github-custom-runners]
x86_64-apple-darwin = "macos-15-intel"
aarch64-unknown-linux-gnu = "ubuntu-24.04-arm"
